# Default values for cc-intel-platform-registration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  repository: local/cc-intel-platform-registration
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

imagePullSecrets:
  - name: biscoito
fullnameOverride: "reg-svc"