version: "3.8"

services:
  cc-intel-platform-registration:
    image: ${REGISTRY:-local}/cc-intel-platform-registration:${VERSION:-demo}
    container_name: cc-intel-platform-registration
    privileged: true
    tty: true
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
    command: [
      "cc-intel-platform-registration", 
      "--zap-log-level=info",
      "--zap-encoder=json",
      "--zap-time-encoding=rfc3339nano"
      ]
    volumes:
      - /sys/firmware/efi/efivars:/sys/firmware/efi/efivars
    environment:
      CC_IPR_REGISTRATION_INTERVAL_MINUTES: "${CC_IPR_REGISTRATION_INTERVAL_MINUTES:-1}"
      CC_IPR_REGISTRATION_SERVICE_PORT: "${CC_SERVICE_PORT:-8080}"
    ports:
      - "${CC_SERVICE_PORT:-8080}:${CC_SERVICE_PORT:-8080}"  
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - cc-intel-platform-registration
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - prometheus_data:/prometheus
      - ${WORK_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    environment:
      - TZ=UTC
 
 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    volumes:
      - grafana_data:/var/lib/grafana
      - ${WORK_DIR}/grafana_datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ${WORK_DIR}/main_dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ${WORK_DIR}/reg_svc.json:/etc/grafana/provisioning/dashboards/reg-svc.json:ro
      
      


      

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

