name: Tag Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  build-main-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make deps

      - name: Run golangci-lint
        run: make docker-lint-check

      - name: Run deadcode check
        run: make docker-deadcode-check

      - name: Run vulnerability check
        run: make docker-vuln-check

      - name: Run tests
        run: make docker-test

      - name: Extract tag name
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Building image with tag: $TAG_NAME"
          echo "IMAGE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Build image with latest tag
        run: make build-image VERSION=${{ env.IMAGE_TAG }} IMG_REGISTRY=ghcr.io/${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository_owner }}/cc-intel-platform-registration:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Run Trivy in GitHub SBOM mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "github"
          output: "dependency-results.sbom.json"
          image-ref: "."
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: make image-push VERSION=${{ env.IMAGE_TAG }} IMG_REGISTRY=ghcr.io/${{ github.repository_owner }}
